import { FoodItem, PurineCategory, PurineLevel } from './types';

function level(mg: number): PurineLevel {
  if (mg <= 100) return 'low';
  if (mg <= 200) return 'moderate';
  if (mg <= 300) return 'high';
  return 'very-high';
}

let idCounter = 0;
function item(
  name: string,
  category: PurineCategory,
  purineContent: number,
  servingSize: string,
  description?: string,
  warnings?: string[]
): FoodItem {
  idCounter++;
  return {
    id: `purine-${idCounter}`,
    name,
    category,
    purineContent,
    purineLevel: level(purineContent),
    servingSize,
    description,
    warnings,
  };
}

export const purineDatabase: FoodItem[] = [
  // ── Organ Meats (Very High) ───────────────────────────────────────────
  item('Liver (Beef)', 'Organ Meats', 554, '100g', 'Beef liver is extremely high in purines.', ['Avoid during flares', 'Limit to rare occasions']),
  item('Liver (Chicken)', 'Organ Meats', 345, '100g', 'Chicken liver is very high in purines.', ['Avoid during flares']),
  item('Liver (Pork)', 'Organ Meats', 515, '100g', 'Pork liver is extremely high in purines.', ['Avoid during flares']),
  item('Kidney (Beef)', 'Organ Meats', 462, '100g', 'Organ meats are among the highest purine foods.', ['Avoid entirely if possible']),
  item('Sweetbreads (Thymus)', 'Organ Meats', 825, '100g', 'One of the highest purine foods.', ['Strictly avoid']),
  item('Heart (Beef)', 'Organ Meats', 256, '100g', 'Beef heart is high in purines.'),
  item('Brain (Beef)', 'Organ Meats', 195, '100g', 'Beef brain has moderate-high purines.'),
  item('Tongue (Beef)', 'Organ Meats', 160, '100g', 'Beef tongue has moderate purines.'),

  // ── Meats ─────────────────────────────────────────────────────────────
  item('Beef (Lean)', 'Meats', 133, '100g', 'Lean beef has moderate purine content.'),
  item('Beef (Ground, 80/20)', 'Meats', 120, '100g', 'Ground beef has moderate purines.'),
  item('Beef (Sirloin)', 'Meats', 140, '100g', 'Sirloin steak has moderate purines.'),
  item('Beef (Ribeye)', 'Meats', 138, '100g', 'Ribeye has moderate purine content.'),
  item('Beef (Chuck Roast)', 'Meats', 125, '100g', 'Chuck roast is moderate in purines.'),
  item('Beef Jerky', 'Meats', 165, '100g', 'Concentrated protein, moderate-high purines.'),
  item('Pork (Loin)', 'Meats', 145, '100g', 'Pork loin has moderate purines.'),
  item('Pork (Chop)', 'Meats', 150, '100g', 'Pork chops are moderate in purines.'),
  item('Pork (Tenderloin)', 'Meats', 141, '100g', 'Lean pork cut with moderate purines.'),
  item('Pork (Shoulder)', 'Meats', 148, '100g', 'Pork shoulder has moderate purines.'),
  item('Pork (Ribs)', 'Meats', 132, '100g', 'Pork ribs have moderate purines.'),
  item('Bacon', 'Meats', 130, '100g', 'Bacon has moderate purines plus high sodium.'),
  item('Ham', 'Meats', 131, '100g', 'Ham has moderate purine content.'),
  item('Sausage (Pork)', 'Meats', 110, '100g', 'Pork sausage has moderate purines.'),
  item('Lamb (Leg)', 'Meats', 182, '100g', 'Lamb leg is moderate-high in purines.'),
  item('Lamb (Chop)', 'Meats', 178, '100g', 'Lamb chops are moderate in purines.'),
  item('Lamb (Shoulder)', 'Meats', 170, '100g', 'Lamb shoulder has moderate purines.'),
  item('Veal', 'Meats', 172, '100g', 'Veal has moderate-high purine content.'),
  item('Venison', 'Meats', 158, '100g', 'Venison is moderate in purines.'),
  item('Bison', 'Meats', 135, '100g', 'Bison is lean with moderate purines.'),
  item('Rabbit', 'Meats', 132, '100g', 'Rabbit has moderate purines.'),
  item('Chicken Breast', 'Meats', 141, '100g', 'Skinless chicken breast has moderate purines.'),
  item('Chicken Thigh', 'Meats', 155, '100g', 'Chicken thigh has slightly more purines.'),
  item('Chicken Wing', 'Meats', 148, '100g', 'Chicken wings have moderate purines.'),
  item('Chicken (Drumstick)', 'Meats', 143, '100g', 'Drumsticks have moderate purines.'),
  item('Turkey Breast', 'Meats', 150, '100g', 'Turkey breast has moderate purines.'),
  item('Turkey (Ground)', 'Meats', 142, '100g', 'Ground turkey has moderate purines.'),
  item('Duck', 'Meats', 165, '100g', 'Duck meat has moderate-high purines.'),
  item('Goose', 'Meats', 165, '100g', 'Goose has moderate-high purines.'),
  item('Hot Dog', 'Meats', 105, '1 frank (57g)', 'Processed meat with moderate purines.'),
  item('Bologna', 'Meats', 100, '100g', 'Processed deli meat with moderate purines.'),
  item('Salami', 'Meats', 120, '100g', 'Cured meat with moderate purines.'),
  item('Pepperoni', 'Meats', 115, '100g', 'Cured meat with moderate purines.'),
  item('Prosciutto', 'Meats', 125, '100g', 'Dry-cured ham with moderate purines.'),
  item('Corned Beef', 'Meats', 128, '100g', 'Cured beef with moderate purines.'),

  // ── Seafood ───────────────────────────────────────────────────────────
  item('Anchovies', 'Seafood', 411, '100g', 'One of the highest purine seafoods.', ['Avoid completely during flares']),
  item('Sardines', 'Seafood', 345, '100g (canned)', 'Very high in purines.', ['Avoid during flares']),
  item('Herring', 'Seafood', 378, '100g', 'Very high in purines.', ['Avoid during flares']),
  item('Mackerel', 'Seafood', 246, '100g', 'High purine content.'),
  item('Mussels', 'Seafood', 310, '100g', 'Very high in purines.', ['Avoid during flares']),
  item('Scallops', 'Seafood', 210, '100g', 'High in purines.'),
  item('Shrimp', 'Seafood', 147, '100g', 'Moderate purine content.'),
  item('Lobster', 'Seafood', 118, '100g', 'Moderate purine content.'),
  item('Crab', 'Seafood', 152, '100g', 'Moderate purine content.'),
  item('Oysters', 'Seafood', 240, '100g', 'High in purines.'),
  item('Clams', 'Seafood', 210, '100g', 'High in purines.'),
  item('Squid (Calamari)', 'Seafood', 135, '100g', 'Moderate purine content.'),
  item('Octopus', 'Seafood', 140, '100g', 'Moderate purine content.'),
  item('Salmon', 'Seafood', 170, '100g', 'Moderate purines but rich in omega-3.'),
  item('Tuna (Fresh)', 'Seafood', 257, '100g', 'High in purines.'),
  item('Tuna (Canned)', 'Seafood', 142, '100g (drained)', 'Moderate purines when canned.'),
  item('Cod', 'Seafood', 109, '100g', 'Lower purine white fish.'),
  item('Tilapia', 'Seafood', 95, '100g', 'Low purine white fish.'),
  item('Haddock', 'Seafood', 119, '100g', 'Moderate purine white fish.'),
  item('Halibut', 'Seafood', 133, '100g', 'Moderate purine content.'),
  item('Trout', 'Seafood', 165, '100g', 'Moderate purine content.'),
  item('Catfish', 'Seafood', 105, '100g', 'Moderate purine white fish.'),
  item('Sea Bass', 'Seafood', 120, '100g', 'Moderate purine content.'),
  item('Swordfish', 'Seafood', 142, '100g', 'Moderate purine content.'),
  item('Snapper', 'Seafood', 110, '100g', 'Moderate purine content.'),
  item('Sole/Flounder', 'Seafood', 95, '100g', 'Low purine flatfish.'),
  item('Perch', 'Seafood', 115, '100g', 'Moderate purine content.'),
  item('Pike', 'Seafood', 105, '100g', 'Moderate purine content.'),
  item('Crayfish', 'Seafood', 150, '100g', 'Moderate purine content.'),
  item('Eel', 'Seafood', 160, '100g', 'Moderate purine content.'),
  item('Smoked Salmon', 'Seafood', 190, '100g', 'Moderate-high purines.'),
  item('Fish Roe/Caviar', 'Seafood', 144, '100g', 'Moderate purines.'),
  item('Surimi (Imitation Crab)', 'Seafood', 45, '100g', 'Low purine processed fish.'),

  // ── Vegetables ────────────────────────────────────────────────────────
  item('Spinach', 'Vegetables', 57, '100g (raw)', 'Lower purine for a leafy green. Generally safe.'),
  item('Asparagus', 'Vegetables', 23, '100g', 'Low purine despite old beliefs.'),
  item('Broccoli', 'Vegetables', 21, '100g', 'Very low purine. Safe for gout.'),
  item('Cauliflower', 'Vegetables', 51, '100g', 'Low purine. Safe for gout.'),
  item('Mushrooms', 'Vegetables', 58, '100g', 'Low-moderate purines. Generally safe.'),
  item('Bell Peppers', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Tomatoes', 'Vegetables', 11, '100g', 'Very low purines.'),
  item('Carrots', 'Vegetables', 17, '100g', 'Very low purines.'),
  item('Celery', 'Vegetables', 18, '100g', 'Very low purines.'),
  item('Cucumber', 'Vegetables', 7, '100g', 'Very low purines.'),
  item('Onions', 'Vegetables', 13, '100g', 'Very low purines.'),
  item('Garlic', 'Vegetables', 15, '100g', 'Very low purines.'),
  item('Zucchini', 'Vegetables', 14, '100g', 'Very low purines.'),
  item('Eggplant', 'Vegetables', 21, '100g', 'Low purines.'),
  item('Green Beans', 'Vegetables', 37, '100g', 'Low purines.'),
  item('Peas (Green)', 'Vegetables', 84, '100g', 'Low-moderate purines.'),
  item('Corn', 'Vegetables', 52, '100g', 'Low purines.'),
  item('Sweet Potato', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Potato', 'Vegetables', 16, '100g', 'Very low purines.'),
  item('Lettuce', 'Vegetables', 13, '100g', 'Very low purines.'),
  item('Kale', 'Vegetables', 48, '100g', 'Low purines.'),
  item('Cabbage', 'Vegetables', 22, '100g', 'Low purines.'),
  item('Brussels Sprouts', 'Vegetables', 69, '100g', 'Low purines.'),
  item('Artichoke', 'Vegetables', 33, '100g', 'Low purines.'),
  item('Beets', 'Vegetables', 19, '100g', 'Very low purines.'),
  item('Radishes', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Turnips', 'Vegetables', 15, '100g', 'Very low purines.'),
  item('Squash (Butternut)', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Pumpkin', 'Vegetables', 14, '100g', 'Very low purines.'),
  item('Avocado', 'Vegetables', 19, '100g', 'Very low purines. Rich in healthy fats.'),
  item('Okra', 'Vegetables', 31, '100g', 'Low purines.'),

  // ── Dairy ─────────────────────────────────────────────────────────────
  item('Milk (Whole)', 'Dairy', 0, '240ml', 'Dairy is very low in purines and may help reduce gout risk.'),
  item('Milk (Skim)', 'Dairy', 0, '240ml', 'Low-fat dairy may help lower uric acid.'),
  item('Yogurt (Plain)', 'Dairy', 1, '170g', 'Very low purines. May help reduce gout risk.'),
  item('Yogurt (Greek)', 'Dairy', 2, '170g', 'Low purines with high protein.'),
  item('Cheese (Cheddar)', 'Dairy', 6, '30g', 'Very low purines.'),
  item('Cheese (Mozzarella)', 'Dairy', 5, '30g', 'Very low purines.'),
  item('Cheese (Swiss)', 'Dairy', 8, '30g', 'Very low purines.'),
  item('Cheese (Parmesan)', 'Dairy', 10, '30g', 'Very low purines.'),
  item('Cheese (Cottage)', 'Dairy', 9, '100g', 'Very low purines.'),
  item('Cheese (Cream)', 'Dairy', 4, '30g', 'Very low purines.'),
  item('Butter', 'Dairy', 0, '14g', 'No purines.'),
  item('Ice Cream', 'Dairy', 3, '100g', 'Very low purines.'),
  item('Sour Cream', 'Dairy', 2, '30g', 'Very low purines.'),
  item('Whey Protein', 'Dairy', 5, '30g scoop', 'Very low purines. Good protein source.'),

  // ── Grains ────────────────────────────────────────────────────────────
  item('White Rice', 'Grains', 18, '100g (cooked)', 'Low purines.'),
  item('Brown Rice', 'Grains', 37, '100g (cooked)', 'Low purines with more fiber.'),
  item('White Bread', 'Grains', 14, '1 slice (30g)', 'Low purines.'),
  item('Whole Wheat Bread', 'Grains', 25, '1 slice (30g)', 'Low purines.'),
  item('Oatmeal', 'Grains', 42, '100g (cooked)', 'Low purines.'),
  item('Pasta (White)', 'Grains', 20, '100g (cooked)', 'Low purines.'),
  item('Pasta (Whole Wheat)', 'Grains', 35, '100g (cooked)', 'Low purines.'),
  item('Cornflakes', 'Grains', 15, '30g', 'Low purines.'),
  item('Quinoa', 'Grains', 25, '100g (cooked)', 'Low purines with complete protein.'),
  item('Barley', 'Grains', 30, '100g (cooked)', 'Low purines.'),
  item('Couscous', 'Grains', 22, '100g (cooked)', 'Low purines.'),
  item('Flour (White)', 'Grains', 18, '100g', 'Low purines.'),
  item('Flour (Whole Wheat)', 'Grains', 35, '100g', 'Low purines.'),
  item('Tortilla (Flour)', 'Grains', 16, '1 tortilla', 'Low purines.'),
  item('Tortilla (Corn)', 'Grains', 14, '1 tortilla', 'Low purines.'),
  item('Bagel', 'Grains', 22, '1 bagel', 'Low purines.'),
  item('Crackers', 'Grains', 20, '30g', 'Low purines.'),
  item('Pancakes', 'Grains', 30, '2 pancakes', 'Low purines.'),
  item('Granola', 'Grains', 38, '50g', 'Low purines.'),
  item('Cereal (Bran)', 'Grains', 42, '40g', 'Low purines with fiber.'),

  // ── Beverages ─────────────────────────────────────────────────────────
  item('Water', 'Beverages', 0, '240ml', 'Essential for flushing uric acid. Aim for 64oz/day.'),
  item('Coffee', 'Beverages', 0, '240ml', 'May help lower uric acid levels.'),
  item('Tea (Green)', 'Beverages', 0, '240ml', 'No purines. Antioxidant benefits.'),
  item('Tea (Black)', 'Beverages', 0, '240ml', 'No purines.'),
  item('Cherry Juice (Tart)', 'Beverages', 0, '240ml', 'May help reduce gout flares.'),
  item('Orange Juice', 'Beverages', 4, '240ml', 'Low purines but high in fructose.', ['Limit due to fructose content']),
  item('Apple Juice', 'Beverages', 2, '240ml', 'Low purines but contains fructose.'),
  item('Soda (Regular)', 'Beverages', 0, '355ml', 'No purines but high fructose raises uric acid.', ['Avoid — fructose increases uric acid']),
  item('Soda (Diet)', 'Beverages', 0, '355ml', 'No purines and no fructose.'),
  item('Milk (as beverage)', 'Beverages', 0, '240ml', 'May help lower uric acid.'),
  item('Smoothie (Fruit)', 'Beverages', 5, '350ml', 'Low purines. Watch fructose content.'),
  item('Coconut Water', 'Beverages', 2, '240ml', 'Low purines. Good hydration.'),
  item('Herbal Tea', 'Beverages', 0, '240ml', 'No purines.'),
  item('Lemonade', 'Beverages', 0, '240ml', 'No purines. Citrus may help.', ['Watch added sugar']),

  // ── Alcohol ───────────────────────────────────────────────────────────
  item('Beer (Regular)', 'Alcohol', 15, '355ml', 'Beer is a major gout trigger due to brewer\'s yeast purines.', ['Major gout trigger', 'Avoid during flares']),
  item('Beer (Light)', 'Alcohol', 10, '355ml', 'Slightly lower purines but still a trigger.', ['Still a gout trigger']),
  item('Beer (Non-Alcoholic)', 'Alcohol', 8, '355ml', 'Still contains yeast-derived purines.'),
  item('Wine (Red)', 'Alcohol', 5, '150ml', 'Lower purine than beer. Moderate amounts may be OK.'),
  item('Wine (White)', 'Alcohol', 3, '150ml', 'Low purines. Better option than beer.'),
  item('Spirits (Vodka, Gin, etc.)', 'Alcohol', 0, '45ml', 'No purines but alcohol impairs uric acid excretion.', ['Alcohol impairs uric acid excretion']),
  item('Whiskey', 'Alcohol', 0, '45ml', 'No purines but alcohol affects uric acid.', ['Alcohol impairs uric acid excretion']),

  // ── Fruits ────────────────────────────────────────────────────────────
  item('Cherries', 'Fruits', 6, '100g', 'May actively help reduce gout flares.'),
  item('Strawberries', 'Fruits', 11, '100g', 'Low purines. Rich in vitamin C.'),
  item('Blueberries', 'Fruits', 12, '100g', 'Low purines. Antioxidant-rich.'),
  item('Raspberries', 'Fruits', 9, '100g', 'Low purines.'),
  item('Blackberries', 'Fruits', 8, '100g', 'Low purines.'),
  item('Grapes', 'Fruits', 8, '100g', 'Low purines.'),
  item('Apple', 'Fruits', 14, '1 medium', 'Low purines.'),
  item('Banana', 'Fruits', 11, '1 medium', 'Low purines. Good potassium source.'),
  item('Orange', 'Fruits', 19, '1 medium', 'Low purines. Vitamin C may help.'),
  item('Lemon', 'Fruits', 5, '1 lemon', 'Very low purines. May alkalinize urine.'),
  item('Lime', 'Fruits', 4, '1 lime', 'Very low purines.'),
  item('Grapefruit', 'Fruits', 8, '1/2 fruit', 'Low purines.', ['May interact with colchicine']),
  item('Watermelon', 'Fruits', 7, '100g', 'Very low purines. Good hydration.'),
  item('Cantaloupe', 'Fruits', 6, '100g', 'Very low purines.'),
  item('Pineapple', 'Fruits', 8, '100g', 'Low purines. Contains bromelain.'),
  item('Mango', 'Fruits', 9, '100g', 'Low purines.'),
  item('Peach', 'Fruits', 12, '1 medium', 'Low purines.'),
  item('Pear', 'Fruits', 12, '1 medium', 'Low purines.'),
  item('Plum', 'Fruits', 10, '1 medium', 'Low purines.'),
  item('Kiwi', 'Fruits', 14, '1 medium', 'Low purines. Rich in vitamin C.'),
  item('Avocado (as fruit)', 'Fruits', 19, '1/2 fruit', 'Low purines.'),
  item('Dried Dates', 'Fruits', 35, '100g', 'Low purines but high in fructose.'),
  item('Raisins', 'Fruits', 25, '40g', 'Low purines.'),
  item('Dried Cranberries', 'Fruits', 18, '40g', 'Low purines.'),
  item('Fig (Dried)', 'Fruits', 32, '100g', 'Low purines.'),

  // ── Nuts & Seeds ──────────────────────────────────────────────────────
  item('Almonds', 'Nuts & Seeds', 37, '30g', 'Low purines. Heart-healthy snack.'),
  item('Walnuts', 'Nuts & Seeds', 25, '30g', 'Low purines. Rich in omega-3.'),
  item('Cashews', 'Nuts & Seeds', 30, '30g', 'Low purines.'),
  item('Peanuts', 'Nuts & Seeds', 42, '30g', 'Low purines.'),
  item('Peanut Butter', 'Nuts & Seeds', 40, '2 tbsp (32g)', 'Low purines.'),
  item('Pecans', 'Nuts & Seeds', 20, '30g', 'Very low purines.'),
  item('Pistachios', 'Nuts & Seeds', 32, '30g', 'Low purines.'),
  item('Macadamia Nuts', 'Nuts & Seeds', 18, '30g', 'Very low purines.'),
  item('Brazil Nuts', 'Nuts & Seeds', 23, '30g', 'Low purines.'),
  item('Hazelnuts', 'Nuts & Seeds', 22, '30g', 'Low purines.'),
  item('Pine Nuts', 'Nuts & Seeds', 30, '30g', 'Low purines.'),
  item('Sunflower Seeds', 'Nuts & Seeds', 65, '30g', 'Low purines.'),
  item('Pumpkin Seeds', 'Nuts & Seeds', 58, '30g', 'Low purines.'),
  item('Flaxseeds', 'Nuts & Seeds', 40, '15g', 'Low purines. Rich in omega-3.'),
  item('Chia Seeds', 'Nuts & Seeds', 35, '15g', 'Low purines. Great fiber source.'),
  item('Sesame Seeds', 'Nuts & Seeds', 55, '15g', 'Low purines.'),
  item('Hemp Seeds', 'Nuts & Seeds', 42, '30g', 'Low purines. Complete protein.'),
  item('Almond Butter', 'Nuts & Seeds', 35, '2 tbsp (32g)', 'Low purines.'),

  // ── Legumes ───────────────────────────────────────────────────────────
  item('Lentils', 'Legumes', 127, '100g (cooked)', 'Moderate purines. Plant protein source.'),
  item('Chickpeas', 'Legumes', 56, '100g (cooked)', 'Low purines.'),
  item('Black Beans', 'Legumes', 70, '100g (cooked)', 'Low purines.'),
  item('Kidney Beans', 'Legumes', 77, '100g (cooked)', 'Low purines.'),
  item('Navy Beans', 'Legumes', 70, '100g (cooked)', 'Low purines.'),
  item('Pinto Beans', 'Legumes', 75, '100g (cooked)', 'Low purines.'),
  item('Lima Beans', 'Legumes', 72, '100g (cooked)', 'Low purines.'),
  item('Soybeans', 'Legumes', 190, '100g (cooked)', 'Moderate purines.'),
  item('Tofu', 'Legumes', 68, '100g', 'Low purines. Good protein alternative.'),
  item('Tempeh', 'Legumes', 85, '100g', 'Low purines. Fermented soy.'),
  item('Edamame', 'Legumes', 70, '100g', 'Low purines.'),
  item('Split Peas', 'Legumes', 95, '100g (cooked)', 'Low purines.'),
  item('Hummus', 'Legumes', 45, '100g', 'Low purines.'),

  // ── Condiments ────────────────────────────────────────────────────────
  item('Olive Oil', 'Condiments', 0, '15ml', 'No purines. Anti-inflammatory.'),
  item('Vinegar', 'Condiments', 0, '15ml', 'No purines.'),
  item('Soy Sauce', 'Condiments', 5, '15ml', 'Very low purines.'),
  item('Mustard', 'Condiments', 8, '15g', 'Very low purines.'),
  item('Ketchup', 'Condiments', 5, '15g', 'Very low purines.'),
  item('Mayonnaise', 'Condiments', 3, '15g', 'Very low purines.'),
  item('Honey', 'Condiments', 0, '15g', 'No purines but contains fructose.'),
  item('Maple Syrup', 'Condiments', 0, '15ml', 'No purines.'),
  item('Hot Sauce', 'Condiments', 2, '5ml', 'Very low purines.'),
  item('Worcestershire Sauce', 'Condiments', 15, '15ml', 'Low purines. Contains anchovies.'),
  item('Gravy (Meat-based)', 'Condiments', 45, '60ml', 'Low-moderate purines from meat drippings.'),
  item('Yeast Extract (Marmite/Vegemite)', 'Condiments', 680, '5g', 'Extremely high in purines!', ['Avoid — extremely high purines']),
  item('Nutritional Yeast', 'Condiments', 290, '15g', 'Very high in purines.', ['Avoid or strictly limit']),

  // ── Snacks ────────────────────────────────────────────────────────────
  item('Eggs', 'Snacks', 2, '1 large', 'Very low purines. Excellent protein source.'),
  item('Cheese & Crackers', 'Snacks', 15, '1 serving', 'Low purines.'),
  item('Dark Chocolate', 'Snacks', 18, '30g', 'Low purines.'),
  item('Milk Chocolate', 'Snacks', 10, '30g', 'Very low purines.'),
  item('Popcorn', 'Snacks', 20, '30g', 'Low purines.'),
  item('Potato Chips', 'Snacks', 15, '30g', 'Low purines.'),
  item('Pretzels', 'Snacks', 12, '30g', 'Low purines.'),
  item('Rice Cakes', 'Snacks', 10, '2 cakes', 'Very low purines.'),
  item('Trail Mix', 'Snacks', 35, '40g', 'Low purines.'),
  item('Granola Bar', 'Snacks', 25, '1 bar', 'Low purines.'),
  item('Fruit Snacks', 'Snacks', 5, '1 pouch', 'Very low purines.'),
  item('Pudding', 'Snacks', 5, '100g', 'Very low purines.'),
  item('Gelatin/Jello', 'Snacks', 2, '100g', 'Very low purines.'),

  // ── Additional Meats ───────────────────────────────────────────────────
  item('Beef Tenderloin', 'Meats', 138, '100g', 'Moderate purines.'),
  item('Beef Sirloin', 'Meats', 146, '100g', 'Moderate purines.'),
  item('Beef Ribeye', 'Meats', 150, '100g', 'Moderate purines.'),
  item('Beef Brisket', 'Meats', 125, '100g', 'Moderate purines.'),
  item('Beef Short Ribs', 'Meats', 152, '100g', 'Moderate purines.'),
  item('Beef Flank Steak', 'Meats', 140, '100g', 'Moderate purines.'),
  item('Beef T-Bone Steak', 'Meats', 148, '100g', 'Moderate purines.'),
  item('Beef Chuck Roast', 'Meats', 120, '100g', 'Moderate purines.'),
  item('Beef Rump Roast', 'Meats', 130, '100g', 'Moderate purines.'),
  item('Corned Beef', 'Meats', 130, '100g', 'Moderate purines.'),
  item('Beef Jerky', 'Meats', 165, '100g', 'Moderate-high purines (concentrated).'),
  item('Pork Tenderloin', 'Meats', 119, '100g', 'Moderate purines.'),
  item('Pork Chops (Bone-In)', 'Meats', 145, '100g', 'Moderate purines.'),
  item('Pork Loin Roast', 'Meats', 130, '100g', 'Moderate purines.'),
  item('Pork Shoulder', 'Meats', 138, '100g', 'Moderate purines.'),
  item('Pork Belly', 'Meats', 110, '100g', 'Moderate purines.'),
  item('Pulled Pork', 'Meats', 135, '100g', 'Moderate purines.'),
  item('Pork Ribs (Baby Back)', 'Meats', 132, '100g', 'Moderate purines.'),
  item('Pork Ribs (Spare)', 'Meats', 140, '100g', 'Moderate purines.'),
  item('Ham Steak', 'Meats', 120, '100g', 'Moderate purines.'),
  item('Canadian Bacon', 'Meats', 105, '100g', 'Moderate purines.'),
  item('Prosciutto', 'Meats', 125, '100g', 'Moderate purines.'),
  item('Chicken Thigh (Skin-On)', 'Meats', 135, '100g', 'Moderate purines.'),
  item('Chicken Drumstick', 'Meats', 130, '100g', 'Moderate purines.'),
  item('Chicken Wing', 'Meats', 140, '100g', 'Moderate purines.'),
  item('Turkey Breast (Smoked)', 'Meats', 140, '100g', 'Moderate purines.'),
  item('Turkey Thigh', 'Meats', 150, '100g', 'Moderate purines.'),
  item('Duck Breast', 'Meats', 165, '100g', 'Moderate-high purines.'),
  item('Duck Leg', 'Meats', 155, '100g', 'Moderate-high purines.'),
  item('Quail', 'Meats', 175, '100g', 'Moderate-high purines.'),
  item('Lamb Loin Chops', 'Meats', 180, '100g', 'Moderate-high purines.'),
  item('Lamb Shanks', 'Meats', 168, '100g', 'Moderate-high purines.'),
  item('Lamb Rack', 'Meats', 175, '100g', 'Moderate-high purines.'),
  item('Goat Meat', 'Meats', 160, '100g', 'Moderate-high purines.'),
  item('Bison/Buffalo', 'Meats', 155, '100g', 'Moderate-high purines.'),
  item('Elk', 'Meats', 165, '100g', 'Moderate-high purines.'),
  item('Rabbit', 'Meats', 145, '100g', 'Moderate purines.'),
  item('Pheasant', 'Meats', 170, '100g', 'Moderate-high purines.'),
  item('Salami', 'Meats', 120, '100g', 'Moderate purines.'),
  item('Pepperoni', 'Meats', 115, '100g', 'Moderate purines.'),
  item('Bologna', 'Meats', 80, '100g', 'Low-moderate purines.'),
  item('Hot Dog (Beef)', 'Meats', 90, '1 link', 'Low-moderate purines.'),
  item('Bratwurst', 'Meats', 105, '1 link', 'Moderate purines.'),
  item('Italian Sausage', 'Meats', 110, '100g', 'Moderate purines.'),
  item('Chorizo', 'Meats', 118, '100g', 'Moderate purines.'),

  // ── Additional Seafood ─────────────────────────────────────────────────
  item('Squid/Calamari', 'Seafood', 135, '100g', 'Moderate purines.'),
  item('Octopus', 'Seafood', 150, '100g', 'Moderate-high purines.'),
  item('Crab (King)', 'Seafood', 152, '100g', 'Moderate-high purines.'),
  item('Crab (Dungeness)', 'Seafood', 148, '100g', 'Moderate purines.'),
  item('Crab (Snow)', 'Seafood', 145, '100g', 'Moderate purines.'),
  item('Lobster Tail', 'Seafood', 118, '100g', 'Moderate purines.'),
  item('Crawfish', 'Seafood', 125, '100g', 'Moderate purines.'),
  item('Clams', 'Seafood', 136, '100g', 'Moderate purines.'),
  item('Oysters', 'Seafood', 120, '100g', 'Moderate purines.'),
  item('Sea Bass', 'Seafood', 110, '100g', 'Moderate purines.'),
  item('Swordfish', 'Seafood', 130, '100g', 'Moderate purines.'),
  item('Mahi Mahi', 'Seafood', 108, '100g', 'Moderate purines.'),
  item('Red Snapper', 'Seafood', 110, '100g', 'Moderate purines.'),
  item('Grouper', 'Seafood', 105, '100g', 'Moderate purines.'),
  item('Halibut', 'Seafood', 126, '100g', 'Moderate purines.'),
  item('Flounder', 'Seafood', 108, '100g', 'Moderate purines.'),
  item('Perch', 'Seafood', 115, '100g', 'Moderate purines.'),
  item('Catfish', 'Seafood', 98, '100g', 'Low purines.'),
  item('Tilapia', 'Seafood', 80, '100g', 'Low purines.'),
  item('Sardines (Fresh)', 'Seafood', 345, '100g', 'Very high purines.', ['Avoid during flares']),
  item('Herring (Fresh)', 'Seafood', 220, '100g', 'High purines.', ['Limit consumption']),
  item('Mackerel (Fresh)', 'Seafood', 246, '100g', 'High purines.', ['Limit consumption']),
  item('Anchovies (Fresh)', 'Seafood', 411, '100g', 'Very high purines.', ['Avoid']),
  item('Eel', 'Seafood', 155, '100g', 'Moderate-high purines.'),
  item('Smoked Salmon (Lox)', 'Seafood', 135, '100g', 'Moderate purines.'),
  item('Fish Sticks (Frozen)', 'Seafood', 75, '100g', 'Low purines.'),
  item('Imitation Crab (Surimi)', 'Seafood', 35, '100g', 'Low purines.'),
  item('Seaweed/Nori', 'Seafood', 45, '10g (dried)', 'Low purines.'),

  // ── Additional Vegetables ──────────────────────────────────────────────
  item('Sweet Potato', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Butternut Squash', 'Vegetables', 10, '100g', 'Very low purines.'),
  item('Acorn Squash', 'Vegetables', 11, '100g', 'Very low purines.'),
  item('Spaghetti Squash', 'Vegetables', 8, '100g', 'Very low purines.'),
  item('Artichoke', 'Vegetables', 18, '100g', 'Low purines.'),
  item('Brussels Sprouts', 'Vegetables', 69, '100g', 'Low purines.'),
  item('Kale', 'Vegetables', 48, '100g', 'Low purines. Rich in vitamin C.'),
  item('Swiss Chard', 'Vegetables', 50, '100g', 'Low purines.'),
  item('Collard Greens', 'Vegetables', 42, '100g', 'Low purines.'),
  item('Bok Choy', 'Vegetables', 22, '100g', 'Low purines.'),
  item('Radish', 'Vegetables', 10, '100g', 'Very low purines.'),
  item('Turnip', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Parsnip', 'Vegetables', 15, '100g', 'Very low purines.'),
  item('Rutabaga', 'Vegetables', 14, '100g', 'Very low purines.'),
  item('Jicama', 'Vegetables', 8, '100g', 'Very low purines.'),
  item('Leek', 'Vegetables', 18, '100g', 'Low purines.'),
  item('Fennel', 'Vegetables', 14, '100g', 'Very low purines.'),
  item('Endive', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Radicchio', 'Vegetables', 10, '100g', 'Very low purines.'),
  item('Watercress', 'Vegetables', 25, '100g', 'Low purines.'),
  item('Arugula', 'Vegetables', 20, '100g', 'Low purines.'),
  item('Okra', 'Vegetables', 28, '100g', 'Low purines.'),
  item('Beets', 'Vegetables', 19, '100g', 'Low purines.'),
  item('Daikon Radish', 'Vegetables', 8, '100g', 'Very low purines.'),
  item('Bean Sprouts', 'Vegetables', 35, '100g', 'Low purines.'),
  item('Bamboo Shoots', 'Vegetables', 18, '100g', 'Low purines.'),
  item('Water Chestnuts', 'Vegetables', 12, '100g', 'Very low purines.'),
  item('Hearts of Palm', 'Vegetables', 10, '100g', 'Very low purines.'),
  item('Kohlrabi', 'Vegetables', 15, '100g', 'Very low purines.'),
  item('Taro Root', 'Vegetables', 18, '100g', 'Low purines.'),

  // ── Additional Fruits ──────────────────────────────────────────────────
  item('Kiwi', 'Fruits', 8, '1 medium', 'Very low purines. High in vitamin C.'),
  item('Papaya', 'Fruits', 7, '100g', 'Very low purines.'),
  item('Passion Fruit', 'Fruits', 10, '100g', 'Very low purines.'),
  item('Guava', 'Fruits', 8, '100g', 'Very low purines. Very high in vitamin C.'),
  item('Lychee', 'Fruits', 6, '100g', 'Very low purines.'),
  item('Dragon Fruit', 'Fruits', 5, '100g', 'Very low purines.'),
  item('Starfruit', 'Fruits', 6, '100g', 'Very low purines.'),
  item('Persimmon', 'Fruits', 8, '100g', 'Very low purines.'),
  item('Pomegranate', 'Fruits', 12, '100g', 'Very low purines. Rich in antioxidants.'),
  item('Figs (Fresh)', 'Fruits', 14, '100g', 'Very low purines.'),
  item('Figs (Dried)', 'Fruits', 30, '100g (dried)', 'Low purines.'),
  item('Dates', 'Fruits', 25, '100g', 'Low purines.'),
  item('Prunes', 'Fruits', 28, '100g', 'Low purines.'),
  item('Cranberries (Fresh)', 'Fruits', 10, '100g', 'Very low purines.'),
  item('Cranberry Juice', 'Fruits', 5, '240ml', 'Very low purines.'),
  item('Apricot (Fresh)', 'Fruits', 10, '100g', 'Very low purines.'),
  item('Apricot (Dried)', 'Fruits', 32, '100g (dried)', 'Low purines.'),
  item('Nectarine', 'Fruits', 8, '1 medium', 'Very low purines.'),
  item('Plum', 'Fruits', 7, '1 medium', 'Very low purines.'),
  item('Tangerine', 'Fruits', 6, '1 medium', 'Very low purines.'),
  item('Cantaloupe', 'Fruits', 7, '100g', 'Very low purines.'),
  item('Honeydew Melon', 'Fruits', 6, '100g', 'Very low purines.'),
  item('Coconut (Fresh)', 'Fruits', 5, '100g', 'Very low purines.'),
  item('Coconut Water', 'Fruits', 3, '240ml', 'Very low purines. Good for hydration.'),

  // ── Additional Dairy ───────────────────────────────────────────────────
  item('Cream Cheese', 'Dairy', 6, '30g', 'Very low purines.'),
  item('Ricotta Cheese', 'Dairy', 12, '100g', 'Very low purines.'),
  item('Goat Cheese', 'Dairy', 10, '30g', 'Very low purines.'),
  item('Brie', 'Dairy', 8, '30g', 'Very low purines.'),
  item('Camembert', 'Dairy', 9, '30g', 'Very low purines.'),
  item('Blue Cheese', 'Dairy', 12, '30g', 'Very low purines.'),
  item('Gouda', 'Dairy', 10, '30g', 'Very low purines.'),
  item('Provolone', 'Dairy', 8, '30g', 'Very low purines.'),
  item('Muenster Cheese', 'Dairy', 7, '30g', 'Very low purines.'),
  item('Havarti', 'Dairy', 8, '30g', 'Very low purines.'),
  item('Sour Cream', 'Dairy', 4, '30g', 'Very low purines.'),
  item('Whipped Cream', 'Dairy', 3, '30g', 'Very low purines.'),
  item('Half & Half', 'Dairy', 5, '30ml', 'Very low purines.'),
  item('Evaporated Milk', 'Dairy', 8, '30ml', 'Very low purines.'),
  item('Condensed Milk', 'Dairy', 10, '30ml', 'Very low purines.'),
  item('Almond Milk', 'Dairy', 2, '240ml', 'Very low purines.'),
  item('Oat Milk', 'Dairy', 8, '240ml', 'Very low purines.'),
  item('Soy Milk', 'Dairy', 20, '240ml', 'Low purines.'),
  item('Kefir', 'Dairy', 12, '240ml', 'Very low purines. Good probiotics.'),
  item('Frozen Yogurt', 'Dairy', 8, '100g', 'Very low purines.'),

  // ── Additional Grains ──────────────────────────────────────────────────
  item('Sourdough Bread', 'Grains', 18, '1 slice', 'Low purines.'),
  item('Pita Bread', 'Grains', 22, '1 pita', 'Low purines.'),
  item('Naan Bread', 'Grains', 25, '1 piece', 'Low purines.'),
  item('Tortilla (Flour)', 'Grains', 18, '1 tortilla', 'Low purines.'),
  item('Tortilla (Corn)', 'Grains', 20, '1 tortilla', 'Low purines.'),
  item('Bagel', 'Grains', 22, '1 bagel', 'Low purines.'),
  item('English Muffin', 'Grains', 20, '1 muffin', 'Low purines.'),
  item('Croissant', 'Grains', 18, '1 croissant', 'Low purines.'),
  item('Biscuit', 'Grains', 16, '1 biscuit', 'Low purines.'),
  item('Cornbread', 'Grains', 22, '1 piece', 'Low purines.'),
  item('Couscous', 'Grains', 30, '100g (cooked)', 'Low purines.'),
  item('Bulgur Wheat', 'Grains', 28, '100g (cooked)', 'Low purines.'),
  item('Farro', 'Grains', 35, '100g (cooked)', 'Low purines.'),
  item('Millet', 'Grains', 30, '100g (cooked)', 'Low purines.'),
  item('Polenta', 'Grains', 22, '100g', 'Low purines.'),
  item('Buckwheat', 'Grains', 40, '100g (cooked)', 'Low purines.'),
  item('Amaranth', 'Grains', 38, '100g (cooked)', 'Low purines.'),
  item('Jasmine Rice', 'Grains', 18, '100g (cooked)', 'Low purines.'),
  item('Basmati Rice', 'Grains', 18, '100g (cooked)', 'Low purines.'),
  item('Wild Rice', 'Grains', 28, '100g (cooked)', 'Low purines.'),
  item('Soba Noodles', 'Grains', 35, '100g (cooked)', 'Low purines.'),
  item('Udon Noodles', 'Grains', 25, '100g (cooked)', 'Low purines.'),
  item('Ramen Noodles', 'Grains', 30, '100g (cooked)', 'Low purines.'),
  item('Egg Noodles', 'Grains', 22, '100g (cooked)', 'Low purines.'),
  item('Rice Noodles', 'Grains', 15, '100g (cooked)', 'Very low purines.'),
  item('Pancake Mix', 'Grains', 18, '1 pancake', 'Low purines.'),
  item('Waffle', 'Grains', 20, '1 waffle', 'Low purines.'),

  // ── Additional Nuts & Seeds ────────────────────────────────────────────
  item('Pecans', 'Nuts & Seeds', 22, '30g', 'Low purines.'),
  item('Macadamia Nuts', 'Nuts & Seeds', 15, '30g', 'Very low purines.'),
  item('Brazil Nuts', 'Nuts & Seeds', 20, '30g', 'Low purines.'),
  item('Hazelnuts', 'Nuts & Seeds', 18, '30g', 'Low purines.'),
  item('Pistachio', 'Nuts & Seeds', 22, '30g', 'Low purines.'),
  item('Hemp Seeds', 'Nuts & Seeds', 28, '30g', 'Low purines.'),
  item('Poppy Seeds', 'Nuts & Seeds', 15, '10g', 'Very low purines.'),
  item('Sesame Seeds', 'Nuts & Seeds', 20, '15g', 'Low purines.'),
  item('Tahini', 'Nuts & Seeds', 25, '30g', 'Low purines.'),
  item('Almond Butter', 'Nuts & Seeds', 22, '30g', 'Low purines.'),
  item('Cashew Butter', 'Nuts & Seeds', 20, '30g', 'Low purines.'),

  // ── Additional Beverages ───────────────────────────────────────────────
  item('Herbal Tea (Chamomile)', 'Beverages', 0, '240ml', 'No purines. Calming.'),
  item('Herbal Tea (Peppermint)', 'Beverages', 0, '240ml', 'No purines.'),
  item('Matcha Tea', 'Beverages', 5, '240ml', 'Very low purines. Rich in antioxidants.'),
  item('Kombucha', 'Beverages', 5, '240ml', 'Very low purines.'),
  item('Hot Chocolate', 'Beverages', 8, '240ml', 'Very low purines.'),
  item('Lemonade', 'Beverages', 3, '240ml', 'Very low purines.'),
  item('Iced Tea (Sweetened)', 'Beverages', 2, '240ml', 'Very low purines.'),
  item('Sparkling Water', 'Beverages', 0, '355ml', 'No purines. Good for hydration.'),
  item('Tonic Water', 'Beverages', 0, '240ml', 'No purines.'),
  item('Ginger Ale', 'Beverages', 0, '355ml', 'No purines.'),
  item('Tomato Juice', 'Beverages', 8, '240ml', 'Very low purines.'),
  item('Vegetable Juice (V8)', 'Beverages', 10, '240ml', 'Very low purines.'),
  item('Protein Shake (Whey)', 'Beverages', 15, '240ml', 'Low purines.'),
  item('Smoothie (Fruit)', 'Beverages', 8, '350ml', 'Very low purines.'),
  item('Coconut Milk (Drink)', 'Beverages', 3, '240ml', 'Very low purines.'),

  // ── Additional Legumes ─────────────────────────────────────────────────
  item('Edamame', 'Legumes', 70, '100g', 'Low purines.'),
  item('Tofu (Firm)', 'Legumes', 68, '100g', 'Low purines. Good protein source.'),
  item('Tofu (Silken)', 'Legumes', 55, '100g', 'Low purines.'),
  item('Tempeh', 'Legumes', 85, '100g', 'Low-moderate purines.'),
  item('Miso', 'Legumes', 40, '15g', 'Low purines.'),
  item('Falafel', 'Legumes', 65, '100g', 'Low purines.'),
  item('Refried Beans', 'Legumes', 75, '100g (cooked)', 'Low purines.'),
  item('Cannellini Beans', 'Legumes', 78, '100g (cooked)', 'Low purines.'),
  item('Great Northern Beans', 'Legumes', 75, '100g (cooked)', 'Low purines.'),
  item('Pinto Beans', 'Legumes', 72, '100g (cooked)', 'Low purines.'),
  item('Lima Beans', 'Legumes', 70, '100g (cooked)', 'Low purines.'),
  item('Butter Beans', 'Legumes', 68, '100g (cooked)', 'Low purines.'),

  // ── Additional Condiments ──────────────────────────────────────────────
  item('Salsa', 'Condiments', 5, '30g', 'Very low purines.'),
  item('Guacamole', 'Condiments', 8, '30g', 'Very low purines.'),
  item('Pesto', 'Condiments', 15, '30g', 'Low purines.'),
  item('Ranch Dressing', 'Condiments', 5, '30ml', 'Very low purines.'),
  item('Italian Dressing', 'Condiments', 3, '30ml', 'Very low purines.'),
  item('Balsamic Vinaigrette', 'Condiments', 2, '30ml', 'Very low purines.'),
  item('Caesar Dressing', 'Condiments', 10, '30ml', 'Very low purines.'),
  item('BBQ Sauce', 'Condiments', 5, '30ml', 'Very low purines.'),
  item('Teriyaki Sauce', 'Condiments', 8, '30ml', 'Very low purines.'),
  item('Hoisin Sauce', 'Condiments', 6, '15ml', 'Very low purines.'),
  item('Fish Sauce', 'Condiments', 35, '15ml', 'Low purines.'),
  item('Oyster Sauce', 'Condiments', 20, '15ml', 'Low purines.'),
  item('Sriracha', 'Condiments', 3, '10ml', 'Very low purines.'),
  item('Chutney (Mango)', 'Condiments', 5, '30g', 'Very low purines.'),
  item('Jam/Jelly', 'Condiments', 2, '15g', 'Very low purines.'),
  item('Peanut Butter', 'Condiments', 22, '30g', 'Low purines.'),
  item('Cream Cheese Spread', 'Condiments', 5, '30g', 'Very low purines.'),
  item('Butter', 'Condiments', 0, '15g', 'No purines.'),
  item('Coconut Oil', 'Condiments', 0, '15ml', 'No purines.'),
  item('Sesame Oil', 'Condiments', 0, '15ml', 'No purines.'),

  // ── Additional Snacks & Prepared Foods ─────────────────────────────────
  item('Pizza (Cheese)', 'Snacks', 45, '1 slice', 'Low-moderate purines.'),
  item('Pizza (Pepperoni)', 'Snacks', 65, '1 slice', 'Moderate purines.'),
  item('French Fries', 'Snacks', 18, '100g', 'Low purines.'),
  item('Onion Rings', 'Snacks', 20, '100g', 'Low purines.'),
  item('Mozzarella Sticks', 'Snacks', 15, '3 pieces', 'Low purines.'),
  item('Nachos with Cheese', 'Snacks', 25, '100g', 'Low purines.'),
  item('Quesadilla (Cheese)', 'Snacks', 30, '1 quesadilla', 'Low purines.'),
  item('Grilled Cheese Sandwich', 'Snacks', 25, '1 sandwich', 'Low purines.'),
  item('Mac and Cheese', 'Snacks', 20, '100g', 'Low purines.'),
  item('Chicken Nuggets', 'Snacks', 80, '100g', 'Low-moderate purines.'),
  item('Fish and Chips', 'Snacks', 85, '1 serving', 'Moderate purines.'),
  item('Spring Rolls', 'Snacks', 30, '2 rolls', 'Low purines.'),
  item('Dumplings (Pork)', 'Snacks', 60, '4 pieces', 'Low-moderate purines.'),
  item('Sushi (Salmon)', 'Snacks', 55, '6 pieces', 'Low-moderate purines.'),
  item('Sushi (Tuna)', 'Snacks', 75, '6 pieces', 'Moderate purines.'),
  item('Sushi (Vegetable)', 'Snacks', 12, '6 pieces', 'Very low purines.'),
  item('Muffin (Blueberry)', 'Snacks', 18, '1 muffin', 'Low purines.'),
  item('Donut', 'Snacks', 15, '1 donut', 'Low purines.'),
  item('Brownie', 'Snacks', 12, '1 brownie', 'Very low purines.'),
  item('Cookie (Chocolate Chip)', 'Snacks', 10, '1 cookie', 'Very low purines.'),
  item('Cake (Vanilla)', 'Snacks', 12, '1 slice', 'Very low purines.'),
  item('Ice Cream', 'Snacks', 8, '100g', 'Very low purines.'),
  item('Popsicle', 'Snacks', 2, '1 bar', 'Very low purines.'),
  item('Cotton Candy', 'Snacks', 0, '30g', 'No purines.'),
  item('Marshmallows', 'Snacks', 0, '30g', 'No purines.'),

  // ── Additional Alcohol ─────────────────────────────────────────────────
  item('IPA Beer', 'Alcohol', 18, '355ml', 'High purines. IPAs tend to be higher.', ['Beer is the highest-risk alcohol for gout', 'Avoid during flares']),
  item('Stout Beer', 'Alcohol', 16, '355ml', 'Moderate purines.', ['Beer is high-risk for gout']),
  item('Wheat Beer', 'Alcohol', 15, '355ml', 'Moderate purines.', ['Beer increases uric acid']),
  item('Hard Cider', 'Alcohol', 8, '355ml', 'Low purines. Better than beer.', ['Moderate alcohol consumption']),
  item('Hard Seltzer', 'Alcohol', 2, '355ml', 'Very low purines.', ['Lower risk than beer']),
  item('Sake', 'Alcohol', 10, '100ml', 'Low purines.', ['Moderate consumption']),
  item('Champagne', 'Alcohol', 5, '150ml', 'Very low purines.', ['Moderate consumption']),
  item('Port Wine', 'Alcohol', 6, '60ml', 'Very low purines.', ['Moderate consumption']),
  item('Brandy', 'Alcohol', 3, '45ml', 'Very low purines.', ['Moderate consumption']),
  item('Tequila', 'Alcohol', 2, '45ml', 'Very low purines.', ['Moderate consumption']),
  item('Rum', 'Alcohol', 2, '45ml', 'Very low purines.', ['Moderate consumption']),
  item('Gin', 'Alcohol', 2, '45ml', 'Very low purines.', ['Moderate consumption']),
  item('Bourbon', 'Alcohol', 3, '45ml', 'Very low purines.', ['Moderate consumption']),
  item('Scotch', 'Alcohol', 3, '45ml', 'Very low purines.', ['Moderate consumption']),

  // ── Additional Organ Meats ─────────────────────────────────────────────
  item('Liver (Lamb)', 'Organ Meats', 480, '100g', 'Very high purines.', ['Avoid entirely']),
  item('Liver (Goose)', 'Organ Meats', 515, '100g', 'Foie gras — very high purines.', ['Avoid entirely']),
  item('Kidney (Pork)', 'Organ Meats', 334, '100g', 'Very high purines.', ['Avoid entirely']),
  item('Kidney (Lamb)', 'Organ Meats', 310, '100g', 'Very high purines.', ['Avoid entirely']),
  item('Tripe', 'Organ Meats', 116, '100g', 'Moderate purines.'),
  item('Tongue (Beef)', 'Organ Meats', 160, '100g', 'Moderate-high purines.'),
  item('Gizzard (Chicken)', 'Organ Meats', 245, '100g', 'High purines.', ['Limit consumption']),
  item('Bone Marrow', 'Organ Meats', 95, '100g', 'Low purines.'),
];

export default purineDatabase;
