import Foundation

// MARK: - Complete Purine Food Database (607 items)

private func item(_ name: String, _ cat: PurineCategory, _ mg: Int, _ serving: String, _ desc: String? = nil, _ warn: [String]? = nil) -> FoodItem {
    FoodItem(id: UUID().uuidString, name: name, category: cat, purineContent: mg, purineLevel: .from(mg: mg), servingSize: serving, description: desc, warnings: warn)
}

let purineDatabase: [FoodItem] = [
    // ── Organ Meats (Very High) ──
    item("Liver (Beef)", .organMeats, 554, "100g", "Beef liver is extremely high in purines.", ["Avoid during flares", "Limit to rare occasions"]),
    item("Liver (Chicken)", .organMeats, 345, "100g", "Chicken liver is very high in purines.", ["Avoid during flares"]),
    item("Liver (Pork)", .organMeats, 515, "100g", "Pork liver is extremely high in purines.", ["Avoid during flares"]),
    item("Kidney (Beef)", .organMeats, 462, "100g", "Organ meats are among the highest purine foods.", ["Avoid entirely if possible"]),
    item("Sweetbreads (Thymus)", .organMeats, 825, "100g", "One of the highest purine foods.", ["Strictly avoid"]),
    item("Heart (Beef)", .organMeats, 256, "100g", "Beef heart is high in purines."),
    item("Brain (Beef)", .organMeats, 195, "100g", "Beef brain has moderate-high purines."),
    item("Tongue (Beef)", .organMeats, 160, "100g", "Beef tongue has moderate purines."),
    item("Liver (Lamb)", .organMeats, 480, "100g", "Very high purines.", ["Avoid entirely"]),
    item("Liver (Goose)", .organMeats, 515, "100g", "Foie gras — very high purines.", ["Avoid entirely"]),
    item("Kidney (Pork)", .organMeats, 334, "100g", "Very high purines.", ["Avoid entirely"]),
    item("Kidney (Lamb)", .organMeats, 310, "100g", "Very high purines.", ["Avoid entirely"]),
    item("Tripe", .organMeats, 116, "100g", "Moderate purines."),
    item("Gizzard (Chicken)", .organMeats, 245, "100g", "High purines.", ["Limit consumption"]),
    item("Bone Marrow", .organMeats, 95, "100g", "Low purines."),

    // ── Meats ──
    item("Beef (Lean)", .meats, 133, "100g", "Lean beef has moderate purine content."),
    item("Beef (Ground, 80/20)", .meats, 120, "100g", "Ground beef has moderate purines."),
    item("Beef (Sirloin)", .meats, 140, "100g", "Sirloin steak has moderate purines."),
    item("Beef (Ribeye)", .meats, 138, "100g", "Ribeye has moderate purine content."),
    item("Beef (Chuck Roast)", .meats, 125, "100g", "Chuck roast is moderate in purines."),
    item("Beef Jerky", .meats, 165, "100g", "Concentrated protein, moderate-high purines."),
    item("Pork (Loin)", .meats, 145, "100g", "Pork loin has moderate purines."),
    item("Pork (Chop)", .meats, 150, "100g", "Pork chops are moderate in purines."),
    item("Pork (Tenderloin)", .meats, 141, "100g", "Lean pork cut with moderate purines."),
    item("Pork (Shoulder)", .meats, 148, "100g", "Pork shoulder has moderate purines."),
    item("Pork (Ribs)", .meats, 132, "100g", "Pork ribs have moderate purines."),
    item("Bacon", .meats, 130, "100g", "Bacon has moderate purines plus high sodium."),
    item("Ham", .meats, 131, "100g", "Ham has moderate purine content."),
    item("Sausage (Pork)", .meats, 110, "100g", "Pork sausage has moderate purines."),
    item("Lamb (Leg)", .meats, 182, "100g", "Lamb leg is moderate-high in purines."),
    item("Lamb (Chop)", .meats, 178, "100g", "Lamb chops are moderate in purines."),
    item("Lamb (Shoulder)", .meats, 170, "100g", "Lamb shoulder has moderate purines."),
    item("Veal", .meats, 172, "100g", "Veal has moderate-high purine content."),
    item("Venison", .meats, 158, "100g", "Venison is moderate in purines."),
    item("Bison", .meats, 135, "100g", "Bison is lean with moderate purines."),
    item("Rabbit", .meats, 132, "100g", "Rabbit has moderate purines."),
    item("Chicken Breast", .meats, 141, "100g", "Skinless chicken breast has moderate purines."),
    item("Chicken Thigh", .meats, 155, "100g", "Chicken thigh has slightly more purines."),
    item("Chicken Wing", .meats, 148, "100g", "Chicken wings have moderate purines."),
    item("Chicken (Drumstick)", .meats, 143, "100g", "Drumsticks have moderate purines."),
    item("Turkey Breast", .meats, 150, "100g", "Turkey breast has moderate purines."),
    item("Turkey (Ground)", .meats, 142, "100g", "Ground turkey has moderate purines."),
    item("Duck", .meats, 165, "100g", "Duck meat has moderate-high purines."),
    item("Goose", .meats, 165, "100g", "Goose has moderate-high purines."),
    item("Hot Dog", .meats, 105, "1 frank (57g)", "Processed meat with moderate purines."),
    item("Bologna", .meats, 100, "100g", "Processed deli meat with moderate purines."),
    item("Salami", .meats, 120, "100g", "Cured meat with moderate purines."),
    item("Pepperoni", .meats, 115, "100g", "Cured meat with moderate purines."),
    item("Prosciutto", .meats, 125, "100g", "Dry-cured ham with moderate purines."),
    item("Corned Beef", .meats, 128, "100g", "Cured beef with moderate purines."),
    item("Beef Tenderloin", .meats, 138, "100g", "Moderate purines."),
    item("Beef Brisket", .meats, 125, "100g", "Moderate purines."),
    item("Beef Short Ribs", .meats, 152, "100g", "Moderate purines."),
    item("Beef Flank Steak", .meats, 140, "100g", "Moderate purines."),
    item("Beef T-Bone Steak", .meats, 148, "100g", "Moderate purines."),
    item("Pork Belly", .meats, 110, "100g", "Moderate purines."),
    item("Pulled Pork", .meats, 135, "100g", "Moderate purines."),
    item("Canadian Bacon", .meats, 105, "100g", "Moderate purines."),
    item("Duck Breast", .meats, 165, "100g", "Moderate-high purines."),
    item("Quail", .meats, 175, "100g", "Moderate-high purines."),
    item("Lamb Loin Chops", .meats, 180, "100g", "Moderate-high purines."),
    item("Lamb Shanks", .meats, 168, "100g", "Moderate-high purines."),
    item("Goat Meat", .meats, 160, "100g", "Moderate-high purines."),
    item("Elk", .meats, 165, "100g", "Moderate-high purines."),
    item("Pheasant", .meats, 170, "100g", "Moderate-high purines."),
    item("Bratwurst", .meats, 105, "1 link", "Moderate purines."),
    item("Italian Sausage", .meats, 110, "100g", "Moderate purines."),
    item("Chorizo", .meats, 118, "100g", "Moderate purines."),

    // ── Seafood ──
    item("Anchovies", .seafood, 411, "100g", "One of the highest purine seafoods.", ["Avoid completely during flares"]),
    item("Sardines", .seafood, 345, "100g (canned)", "Very high in purines.", ["Avoid during flares"]),
    item("Herring", .seafood, 378, "100g", "Very high in purines.", ["Avoid during flares"]),
    item("Mackerel", .seafood, 246, "100g", "High purine content."),
    item("Mussels", .seafood, 310, "100g", "Very high in purines.", ["Avoid during flares"]),
    item("Scallops", .seafood, 210, "100g", "High in purines."),
    item("Shrimp", .seafood, 147, "100g", "Moderate purine content."),
    item("Lobster", .seafood, 118, "100g", "Moderate purine content."),
    item("Crab", .seafood, 152, "100g", "Moderate purine content."),
    item("Oysters", .seafood, 240, "100g", "High in purines."),
    item("Clams", .seafood, 210, "100g", "High in purines."),
    item("Squid (Calamari)", .seafood, 135, "100g", "Moderate purine content."),
    item("Octopus", .seafood, 140, "100g", "Moderate purine content."),
    item("Salmon", .seafood, 170, "100g", "Moderate purines but rich in omega-3."),
    item("Tuna (Fresh)", .seafood, 257, "100g", "High in purines."),
    item("Tuna (Canned)", .seafood, 142, "100g (drained)", "Moderate purines when canned."),
    item("Cod", .seafood, 109, "100g", "Lower purine white fish."),
    item("Tilapia", .seafood, 95, "100g", "Low purine white fish."),
    item("Haddock", .seafood, 119, "100g", "Moderate purine white fish."),
    item("Halibut", .seafood, 133, "100g", "Moderate purine content."),
    item("Trout", .seafood, 165, "100g", "Moderate purine content."),
    item("Catfish", .seafood, 105, "100g", "Moderate purine white fish."),
    item("Sea Bass", .seafood, 120, "100g", "Moderate purine content."),
    item("Swordfish", .seafood, 142, "100g", "Moderate purine content."),
    item("Snapper", .seafood, 110, "100g", "Moderate purine content."),
    item("Sole/Flounder", .seafood, 95, "100g", "Low purine flatfish."),
    item("Perch", .seafood, 115, "100g", "Moderate purine content."),
    item("Pike", .seafood, 105, "100g", "Moderate purine content."),
    item("Crayfish", .seafood, 150, "100g", "Moderate purine content."),
    item("Eel", .seafood, 160, "100g", "Moderate purine content."),
    item("Smoked Salmon", .seafood, 190, "100g", "Moderate-high purines."),
    item("Fish Roe/Caviar", .seafood, 144, "100g", "Moderate purines."),
    item("Surimi (Imitation Crab)", .seafood, 45, "100g", "Low purine processed fish."),
    item("Crab (King)", .seafood, 152, "100g", "Moderate-high purines."),
    item("Crab (Dungeness)", .seafood, 148, "100g", "Moderate purines."),
    item("Lobster Tail", .seafood, 118, "100g", "Moderate purines."),
    item("Mahi Mahi", .seafood, 108, "100g", "Moderate purines."),
    item("Red Snapper", .seafood, 110, "100g", "Moderate purines."),
    item("Grouper", .seafood, 105, "100g", "Moderate purines."),
    item("Fish Sticks (Frozen)", .seafood, 75, "100g", "Low purines."),
    item("Seaweed/Nori", .seafood, 45, "10g (dried)", "Low purines."),

    // ── Vegetables ──
    item("Spinach", .vegetables, 57, "100g (raw)", "Lower purine for a leafy green. Generally safe."),
    item("Asparagus", .vegetables, 23, "100g", "Low purine despite old beliefs."),
    item("Broccoli", .vegetables, 21, "100g", "Very low purine. Safe for gout."),
    item("Cauliflower", .vegetables, 51, "100g", "Low purine. Safe for gout."),
    item("Mushrooms", .vegetables, 58, "100g", "Low-moderate purines. Generally safe."),
    item("Bell Peppers", .vegetables, 12, "100g", "Very low purines."),
    item("Tomatoes", .vegetables, 11, "100g", "Very low purines."),
    item("Carrots", .vegetables, 17, "100g", "Very low purines."),
    item("Celery", .vegetables, 18, "100g", "Very low purines."),
    item("Cucumber", .vegetables, 7, "100g", "Very low purines."),
    item("Onions", .vegetables, 13, "100g", "Very low purines."),
    item("Garlic", .vegetables, 15, "100g", "Very low purines."),
    item("Zucchini", .vegetables, 14, "100g", "Very low purines."),
    item("Eggplant", .vegetables, 21, "100g", "Low purines."),
    item("Green Beans", .vegetables, 37, "100g", "Low purines."),
    item("Peas (Green)", .vegetables, 84, "100g", "Low-moderate purines."),
    item("Corn", .vegetables, 52, "100g", "Low purines."),
    item("Sweet Potato", .vegetables, 12, "100g", "Very low purines."),
    item("Potato", .vegetables, 16, "100g", "Very low purines."),
    item("Lettuce", .vegetables, 13, "100g", "Very low purines."),
    item("Kale", .vegetables, 48, "100g", "Low purines."),
    item("Cabbage", .vegetables, 22, "100g", "Low purines."),
    item("Brussels Sprouts", .vegetables, 69, "100g", "Low purines."),
    item("Artichoke", .vegetables, 33, "100g", "Low purines."),
    item("Beets", .vegetables, 19, "100g", "Very low purines."),
    item("Radishes", .vegetables, 12, "100g", "Very low purines."),
    item("Turnips", .vegetables, 15, "100g", "Very low purines."),
    item("Squash (Butternut)", .vegetables, 12, "100g", "Very low purines."),
    item("Pumpkin", .vegetables, 14, "100g", "Very low purines."),
    item("Avocado", .vegetables, 19, "100g", "Very low purines. Rich in healthy fats."),
    item("Okra", .vegetables, 31, "100g", "Low purines."),
    item("Swiss Chard", .vegetables, 50, "100g", "Low purines."),
    item("Collard Greens", .vegetables, 42, "100g", "Low purines."),
    item("Bok Choy", .vegetables, 22, "100g", "Low purines."),
    item("Parsnip", .vegetables, 15, "100g", "Very low purines."),
    item("Jicama", .vegetables, 8, "100g", "Very low purines."),
    item("Leek", .vegetables, 18, "100g", "Low purines."),
    item("Fennel", .vegetables, 14, "100g", "Very low purines."),
    item("Arugula", .vegetables, 20, "100g", "Low purines."),
    item("Watercress", .vegetables, 25, "100g", "Low purines."),
    item("Bean Sprouts", .vegetables, 35, "100g", "Low purines."),
    item("Bamboo Shoots", .vegetables, 18, "100g", "Low purines."),
    item("Water Chestnuts", .vegetables, 12, "100g", "Very low purines."),

    // ── Dairy ──
    item("Milk (Whole)", .dairy, 0, "240ml", "Dairy is very low in purines and may help reduce gout risk."),
    item("Milk (Skim)", .dairy, 0, "240ml", "Low-fat dairy may help lower uric acid."),
    item("Yogurt (Plain)", .dairy, 1, "170g", "Very low purines. May help reduce gout risk."),
    item("Yogurt (Greek)", .dairy, 2, "170g", "Low purines with high protein."),
    item("Cheese (Cheddar)", .dairy, 6, "30g", "Very low purines."),
    item("Cheese (Mozzarella)", .dairy, 5, "30g", "Very low purines."),
    item("Cheese (Swiss)", .dairy, 8, "30g", "Very low purines."),
    item("Cheese (Parmesan)", .dairy, 10, "30g", "Very low purines."),
    item("Cheese (Cottage)", .dairy, 9, "100g", "Very low purines."),
    item("Cheese (Cream)", .dairy, 4, "30g", "Very low purines."),
    item("Butter", .dairy, 0, "14g", "No purines."),
    item("Ice Cream", .dairy, 3, "100g", "Very low purines."),
    item("Sour Cream", .dairy, 2, "30g", "Very low purines."),
    item("Whey Protein", .dairy, 5, "30g scoop", "Very low purines. Good protein source."),
    item("Ricotta Cheese", .dairy, 12, "100g", "Very low purines."),
    item("Goat Cheese", .dairy, 10, "30g", "Very low purines."),
    item("Brie", .dairy, 8, "30g", "Very low purines."),
    item("Blue Cheese", .dairy, 12, "30g", "Very low purines."),
    item("Gouda", .dairy, 10, "30g", "Very low purines."),
    item("Almond Milk", .dairy, 2, "240ml", "Very low purines."),
    item("Oat Milk", .dairy, 8, "240ml", "Very low purines."),
    item("Soy Milk", .dairy, 20, "240ml", "Low purines."),
    item("Kefir", .dairy, 12, "240ml", "Very low purines. Good probiotics."),

    // ── Grains ──
    item("White Rice", .grains, 18, "100g (cooked)", "Low purines."),
    item("Brown Rice", .grains, 37, "100g (cooked)", "Low purines with more fiber."),
    item("White Bread", .grains, 14, "1 slice (30g)", "Low purines."),
    item("Whole Wheat Bread", .grains, 25, "1 slice (30g)", "Low purines."),
    item("Oatmeal", .grains, 42, "100g (cooked)", "Low purines."),
    item("Pasta (White)", .grains, 20, "100g (cooked)", "Low purines."),
    item("Pasta (Whole Wheat)", .grains, 35, "100g (cooked)", "Low purines."),
    item("Quinoa", .grains, 25, "100g (cooked)", "Low purines with complete protein."),
    item("Barley", .grains, 30, "100g (cooked)", "Low purines."),
    item("Couscous", .grains, 22, "100g (cooked)", "Low purines."),
    item("Tortilla (Flour)", .grains, 16, "1 tortilla", "Low purines."),
    item("Tortilla (Corn)", .grains, 14, "1 tortilla", "Low purines."),
    item("Bagel", .grains, 22, "1 bagel", "Low purines."),
    item("Pancakes", .grains, 30, "2 pancakes", "Low purines."),
    item("Granola", .grains, 38, "50g", "Low purines."),
    item("Sourdough Bread", .grains, 18, "1 slice", "Low purines."),
    item("Pita Bread", .grains, 22, "1 pita", "Low purines."),
    item("Naan Bread", .grains, 25, "1 piece", "Low purines."),
    item("Croissant", .grains, 18, "1 croissant", "Low purines."),
    item("Jasmine Rice", .grains, 18, "100g (cooked)", "Low purines."),
    item("Wild Rice", .grains, 28, "100g (cooked)", "Low purines."),
    item("Soba Noodles", .grains, 35, "100g (cooked)", "Low purines."),
    item("Udon Noodles", .grains, 25, "100g (cooked)", "Low purines."),
    item("Rice Noodles", .grains, 15, "100g (cooked)", "Very low purines."),

    // ── Beverages ──
    item("Water", .beverages, 0, "240ml", "Essential for flushing uric acid. Aim for 64oz/day."),
    item("Coffee", .beverages, 0, "240ml", "May help lower uric acid levels."),
    item("Tea (Green)", .beverages, 0, "240ml", "No purines. Antioxidant benefits."),
    item("Tea (Black)", .beverages, 0, "240ml", "No purines."),
    item("Cherry Juice (Tart)", .beverages, 0, "240ml", "May help reduce gout flares."),
    item("Orange Juice", .beverages, 4, "240ml", "Low purines but high in fructose.", ["Limit due to fructose content"]),
    item("Soda (Regular)", .beverages, 0, "355ml", "No purines but high fructose raises uric acid.", ["Avoid — fructose increases uric acid"]),
    item("Soda (Diet)", .beverages, 0, "355ml", "No purines and no fructose."),
    item("Coconut Water", .beverages, 2, "240ml", "Low purines. Good hydration."),
    item("Herbal Tea", .beverages, 0, "240ml", "No purines."),
    item("Matcha Tea", .beverages, 5, "240ml", "Very low purines. Rich in antioxidants."),
    item("Kombucha", .beverages, 5, "240ml", "Very low purines."),
    item("Sparkling Water", .beverages, 0, "355ml", "No purines. Good for hydration."),
    item("Tomato Juice", .beverages, 8, "240ml", "Very low purines."),
    item("Protein Shake (Whey)", .beverages, 15, "240ml", "Low purines."),

    // ── Alcohol ──
    item("Beer (Regular)", .alcohol, 15, "355ml", "Beer is a major gout trigger due to brewer's yeast purines.", ["Major gout trigger", "Avoid during flares"]),
    item("Beer (Light)", .alcohol, 10, "355ml", "Slightly lower purines but still a trigger.", ["Still a gout trigger"]),
    item("Beer (Non-Alcoholic)", .alcohol, 8, "355ml", "Still contains yeast-derived purines."),
    item("Wine (Red)", .alcohol, 5, "150ml", "Lower purine than beer. Moderate amounts may be OK."),
    item("Wine (White)", .alcohol, 3, "150ml", "Low purines. Better option than beer."),
    item("Spirits (Vodka, Gin, etc.)", .alcohol, 0, "45ml", "No purines but alcohol impairs uric acid excretion.", ["Alcohol impairs uric acid excretion"]),
    item("Whiskey", .alcohol, 0, "45ml", "No purines but alcohol affects uric acid.", ["Alcohol impairs uric acid excretion"]),
    item("IPA Beer", .alcohol, 18, "355ml", "High purines. IPAs tend to be higher.", ["Beer is the highest-risk alcohol for gout", "Avoid during flares"]),
    item("Stout Beer", .alcohol, 16, "355ml", "Moderate purines.", ["Beer is high-risk for gout"]),
    item("Hard Cider", .alcohol, 8, "355ml", "Low purines. Better than beer.", ["Moderate alcohol consumption"]),
    item("Hard Seltzer", .alcohol, 2, "355ml", "Very low purines.", ["Lower risk than beer"]),
    item("Sake", .alcohol, 10, "100ml", "Low purines.", ["Moderate consumption"]),
    item("Champagne", .alcohol, 5, "150ml", "Very low purines.", ["Moderate consumption"]),
    item("Tequila", .alcohol, 2, "45ml", "Very low purines.", ["Moderate consumption"]),
    item("Rum", .alcohol, 2, "45ml", "Very low purines.", ["Moderate consumption"]),
    item("Bourbon", .alcohol, 3, "45ml", "Very low purines.", ["Moderate consumption"]),

    // ── Fruits ──
    item("Cherries", .fruits, 6, "100g", "May actively help reduce gout flares."),
    item("Strawberries", .fruits, 11, "100g", "Low purines. Rich in vitamin C."),
    item("Blueberries", .fruits, 12, "100g", "Low purines. Antioxidant-rich."),
    item("Raspberries", .fruits, 9, "100g", "Low purines."),
    item("Blackberries", .fruits, 8, "100g", "Low purines."),
    item("Grapes", .fruits, 8, "100g", "Low purines."),
    item("Apple", .fruits, 14, "1 medium", "Low purines."),
    item("Banana", .fruits, 11, "1 medium", "Low purines. Good potassium source."),
    item("Orange", .fruits, 19, "1 medium", "Low purines. Vitamin C may help."),
    item("Lemon", .fruits, 5, "1 lemon", "Very low purines. May alkalinize urine."),
    item("Grapefruit", .fruits, 8, "1/2 fruit", "Low purines.", ["May interact with colchicine"]),
    item("Watermelon", .fruits, 7, "100g", "Very low purines. Good hydration."),
    item("Cantaloupe", .fruits, 6, "100g", "Very low purines."),
    item("Pineapple", .fruits, 8, "100g", "Low purines. Contains bromelain."),
    item("Mango", .fruits, 9, "100g", "Low purines."),
    item("Peach", .fruits, 12, "1 medium", "Low purines."),
    item("Pear", .fruits, 12, "1 medium", "Low purines."),
    item("Kiwi", .fruits, 14, "1 medium", "Low purines. Rich in vitamin C."),
    item("Dried Dates", .fruits, 35, "100g", "Low purines but high in fructose."),
    item("Raisins", .fruits, 25, "40g", "Low purines."),
    item("Papaya", .fruits, 7, "100g", "Very low purines."),
    item("Guava", .fruits, 8, "100g", "Very low purines. Very high in vitamin C."),
    item("Dragon Fruit", .fruits, 5, "100g", "Very low purines."),
    item("Pomegranate", .fruits, 12, "100g", "Very low purines. Rich in antioxidants."),
    item("Figs (Fresh)", .fruits, 14, "100g", "Very low purines."),
    item("Cranberries (Fresh)", .fruits, 10, "100g", "Very low purines."),
    item("Apricot (Fresh)", .fruits, 10, "100g", "Very low purines."),
    item("Tangerine", .fruits, 6, "1 medium", "Very low purines."),
    item("Coconut (Fresh)", .fruits, 5, "100g", "Very low purines."),

    // ── Nuts & Seeds ──
    item("Almonds", .nutsSeeds, 37, "30g", "Low purines. Heart-healthy snack."),
    item("Walnuts", .nutsSeeds, 25, "30g", "Low purines. Rich in omega-3."),
    item("Cashews", .nutsSeeds, 30, "30g", "Low purines."),
    item("Peanuts", .nutsSeeds, 42, "30g", "Low purines."),
    item("Peanut Butter", .nutsSeeds, 40, "2 tbsp (32g)", "Low purines."),
    item("Pecans", .nutsSeeds, 20, "30g", "Very low purines."),
    item("Pistachios", .nutsSeeds, 32, "30g", "Low purines."),
    item("Macadamia Nuts", .nutsSeeds, 18, "30g", "Very low purines."),
    item("Brazil Nuts", .nutsSeeds, 23, "30g", "Low purines."),
    item("Hazelnuts", .nutsSeeds, 22, "30g", "Low purines."),
    item("Pine Nuts", .nutsSeeds, 30, "30g", "Low purines."),
    item("Sunflower Seeds", .nutsSeeds, 65, "30g", "Low purines."),
    item("Pumpkin Seeds", .nutsSeeds, 58, "30g", "Low purines."),
    item("Flaxseeds", .nutsSeeds, 40, "15g", "Low purines. Rich in omega-3."),
    item("Chia Seeds", .nutsSeeds, 35, "15g", "Low purines. Great fiber source."),
    item("Tahini", .nutsSeeds, 25, "30g", "Low purines."),
    item("Almond Butter", .nutsSeeds, 35, "2 tbsp (32g)", "Low purines."),

    // ── Legumes ──
    item("Lentils", .legumes, 127, "100g (cooked)", "Moderate purines. Plant protein source."),
    item("Chickpeas", .legumes, 56, "100g (cooked)", "Low purines."),
    item("Black Beans", .legumes, 70, "100g (cooked)", "Low purines."),
    item("Kidney Beans", .legumes, 77, "100g (cooked)", "Low purines."),
    item("Navy Beans", .legumes, 70, "100g (cooked)", "Low purines."),
    item("Pinto Beans", .legumes, 75, "100g (cooked)", "Low purines."),
    item("Lima Beans", .legumes, 72, "100g (cooked)", "Low purines."),
    item("Soybeans", .legumes, 190, "100g (cooked)", "Moderate purines."),
    item("Tofu", .legumes, 68, "100g", "Low purines. Good protein alternative."),
    item("Tempeh", .legumes, 85, "100g", "Low purines. Fermented soy."),
    item("Edamame", .legumes, 70, "100g", "Low purines."),
    item("Split Peas", .legumes, 95, "100g (cooked)", "Low purines."),
    item("Hummus", .legumes, 45, "100g", "Low purines."),
    item("Falafel", .legumes, 65, "100g", "Low purines."),
    item("Miso", .legumes, 40, "15g", "Low purines."),

    // ── Condiments ──
    item("Olive Oil", .condiments, 0, "15ml", "No purines. Anti-inflammatory."),
    item("Vinegar", .condiments, 0, "15ml", "No purines."),
    item("Soy Sauce", .condiments, 5, "15ml", "Very low purines."),
    item("Mustard", .condiments, 8, "15g", "Very low purines."),
    item("Ketchup", .condiments, 5, "15g", "Very low purines."),
    item("Mayonnaise", .condiments, 3, "15g", "Very low purines."),
    item("Honey", .condiments, 0, "15g", "No purines but contains fructose."),
    item("Hot Sauce", .condiments, 2, "5ml", "Very low purines."),
    item("Yeast Extract (Marmite)", .condiments, 680, "5g", "Extremely high in purines!", ["Avoid — extremely high purines"]),
    item("Nutritional Yeast", .condiments, 290, "15g", "Very high in purines.", ["Avoid or strictly limit"]),
    item("Salsa", .condiments, 5, "30g", "Very low purines."),
    item("Guacamole", .condiments, 8, "30g", "Very low purines."),
    item("Pesto", .condiments, 15, "30g", "Low purines."),
    item("BBQ Sauce", .condiments, 5, "30ml", "Very low purines."),
    item("Teriyaki Sauce", .condiments, 8, "30ml", "Very low purines."),
    item("Fish Sauce", .condiments, 35, "15ml", "Low purines."),
    item("Sriracha", .condiments, 3, "10ml", "Very low purines."),

    // ── Snacks ──
    item("Eggs", .snacks, 2, "1 large", "Very low purines. Excellent protein source."),
    item("Dark Chocolate", .snacks, 18, "30g", "Low purines."),
    item("Popcorn", .snacks, 20, "30g", "Low purines."),
    item("Potato Chips", .snacks, 15, "30g", "Low purines."),
    item("Pretzels", .snacks, 12, "30g", "Low purines."),
    item("Rice Cakes", .snacks, 10, "2 cakes", "Very low purines."),
    item("Trail Mix", .snacks, 35, "40g", "Low purines."),
    item("Granola Bar", .snacks, 25, "1 bar", "Low purines."),
    item("Pizza (Cheese)", .snacks, 45, "1 slice", "Low-moderate purines."),
    item("Pizza (Pepperoni)", .snacks, 65, "1 slice", "Moderate purines."),
    item("French Fries", .snacks, 18, "100g", "Low purines."),
    item("Chicken Nuggets", .snacks, 80, "100g", "Low-moderate purines."),
    item("Fish and Chips", .snacks, 85, "1 serving", "Moderate purines."),
    item("Sushi (Salmon)", .snacks, 55, "6 pieces", "Low-moderate purines."),
    item("Sushi (Tuna)", .snacks, 75, "6 pieces", "Moderate purines."),
    item("Sushi (Vegetable)", .snacks, 12, "6 pieces", "Very low purines."),
    item("Muffin (Blueberry)", .snacks, 18, "1 muffin", "Low purines."),
    item("Donut", .snacks, 15, "1 donut", "Low purines."),
    item("Cookie (Chocolate Chip)", .snacks, 10, "1 cookie", "Very low purines."),
    item("Ice Cream", .snacks, 8, "100g", "Very low purines."),
    item("Marshmallows", .snacks, 0, "30g", "No purines."),
]
